version: '3'
services:
  GolangApiServer:
    image: skrjmn/go-app-api
    container_name: GolangApiServer
    restart: unless-stopped
    ports:
      - "5005:5005"
    networks:
      - app-network
    depends_on:
      - mongodb
  VueServer:
    image: skrjmn/vue-app-fe
    container_name: VueServer
    restart: unless-stopped
    ports:
      - "1024:80"
    networks:
      - app-network
    volumes:
      - dist:/dist
    depends_on:
      - GolangApiServer
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/usr/data/db
    networks:
      - app-network

volumes:
  dist:
    driver: local
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge