name: 'Setup backend Environment'
description: 'Sets up go env and install backend dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
  
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.1'

    - name: Cach Go Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Dependencies
      run: |
        go mod tidy
        go mod download
      working-directory: ./backend/api
      shell: bash

    - name: Install test Dependencies
      run: go get -t ./tests/...
      working-directory: ./backend/api
      shell: bash