name : Backend Tests

on:
  push:
    branches: [main, auto-testing]
  pull_request:
    branches: [main, auto-testing]

jobs:
  backend-tests:
    name: Backend Go Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26.1'
      - name: Cach Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download
        working-directory: ./backend/api
  
      - name: Install test Dependencies
        run: go get -t ./tests/...
        working-directory: ./backend/api

      - name: Wait For MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "waiting for mongodb"
            sleep 2
          done
          echo "mongodb is ready"

      - name: Run Go Tests
        run: go test -v ./tests/...
        working-directory: ./backend/api
        env:
          TEST_MONGO_URI: mongodb://localhost:27017