name: CI/CD Pipeline

on:
  push:
    branches: [main, auto-testing]
  pull_request:
    branches: [main, auto-testing]

jobs:
  backend-tests:
    uses: ./.github/workflows/backend-tests.yml
    secrets: inherit

  integration-frontend-tests:
    uses: ./.github/workflows/integration-tests.yml
    needs: backend-tests
    secrets: inherit