name: Deploy Images To  Docker Hub

on:
  workflow_call:

env:
  DOCKER_REPO_BACK_API: "go-app-api"
  DOCKER_REPO_FRONTEND: "vue-app-fe"
  DOCKER_TAG: "latest"


jobs:
  deploy-to-dockerhub:
    name: deploy to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: build backend image
        run: |
          docker build ./backend/api --file ./backend/api/Dockerfile --tag ${{ secrets.DOCKER_USER }}/$DOCKER_REPO_BACK_API:$DOCKER_TAG
      - name: push backend image to docker hub
        run: |
          docker push ${{secrets.DOCKER_USER}}/$DOCKER_REPO_BACK_API:$DOCKER_TAG
      
      - name: build frontend image
        run: |
          docker build ./frontend --file ./frontend/Dockerfile --tag ${{ secrets.DOCKER_USER }}/$DOCKER_REPO_FRONTEND:$DOCKER_TAG
      - name: push frontend image to docker hub
        run: |
          docker push ${{secrets.DOCKER_USER}}/$DOCKER_REPO_FRONTEND:$DOCKER_TAG